DATABASE_NAME = "Vaccinations"
PATIENT_COLLECTION = "PatientData"
DEVELOPMENT_COLLECTION = "DevelopmentHelp"
DATABASE_ADMIN_USERNAME = "admin"
DATABASE_ADMIN_PASSWORD = "j4WCECBtMpdkwSKi"
QR_CODE_ID = "QRCodeData"
QR_CODE_REQUEST_PARAM = "qr"

